apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - production_configMap.yaml
patches:
  - path: replica_count.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
