apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-deployment
  namespace: flux-system
spec:
  interval: 5m
  path: "./deploy/grafana"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # Assumes your configuration files are managed within a GitRepository in the same namespace.
  dependsOn:
    - name: grafana  # Ensures Helm chart is fetched and available before applying the Kustomization.
