---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 1m0s
  url: ssh://git@github.com/smacacademy4all/case1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2024-04-23T15:37:09.0880887+05:30"
  name: webapp-latest
  namespace: flux-system
spec:
  interval: 3m0s
  ref:
    branch: master
  timeout: 1m0s
  url: https://github.com/smacacademy4all/podinfo
