apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: backend
  namespace: flux-system
spec:
  interval: 5m
  path: "./0-Demo-Files/9-kustomize-health-check/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  healthChecks:
    - kind: Deployment
      name: redis
      namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: backend
  path: "./0-Demo-Files/9-kustomize-health-check/podinfo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  healthChecks:
    - kind: Deployment
      name: podinfo
      namespace: default
